### ISSUE TITLE
Warning for incomplete papers, containing only title and abstract

### ISSUE THREAD

**Issue by tsantalis** [acmsigsoft/submission-checker#1]
Sometimes authors submit along with the abstract submission a pdf file containing only the title and abstract of the paper.
If they miss the paper submission deadline without withdrawing the paper, pdfchecker gives no warning.
This feature is more useful for conferences that have a separate deadline for the abstract submission, followed by another deadline for the paper submission.
In general, it would be nice to have a warning for suspicious short papers.

**Comment by avandeursen** [comment]
That's a good idea. I'll indeed add a warning for papers that are very short (1-2 pages) when the call asks for 10.

**Comment by tsantalis** [comment]
Thank you @avandeursen 
This fix might also catch papers that were submitted by mistake to the Research Track, while they were intended for tracks with lower page limits, such as ERA, NIER tracks.
