### ISSUE TITLE
Wrong Usage code section in README.md

### ISSUE THREAD

**Issue by george1459** [acmsigsoft/submission-checker#2]
In the Usage section, these two lines are given out

`unzip  submission-checker-{version}-jar-with-depencies.jar.zip
java -jar submission-checker-{version}-jar-with-depencies.jar --help`

This misspells the word **dependencies** and does not match the file name `submission-checker-0.3.0-jar-with-dependencies.jar.zip` in latest release.

**Comment by avandeursen** [comment]
Thanks!

Better way of releasing would be to distribute jar via github actions -- that's a todo item.
